import time
from LamdaAutomation.Utils import instaloginLibrary
from LamdaAutomation.Utils import instaLanguageLibrary

aj2 = instaloginLibrary.instaloginLibrary()
aj3 = instaLanguageLibrary.instaLanguageLibrary()

aj2.screenOnUi()
time.sleep(2)
aj2.screenSwipeADB()
time.sleep(2)
aj2.launchApp()
time.sleep(2)
aj3.clickProfileUi()
time.sleep(3)
aj3.clickByMenuUi()
time.sleep(3)
aj3.clickBySettingsUi()
time.sleep(4)
aj3.clickLanguageUi()
time.sleep(3)
aj3.searchLanguageUi()
time.sleep(3)
aj3.langInputTeluguADB()
time.sleep(4)
aj3.clickUi()
time.sleep(5)
aj3.clickLanguageUi()
time.sleep(5)
aj3.searchEnglishLangUi()
time.sleep(5)
aj3.languageInputEnglishADB()
time.sleep(5)
aj3.clickUi()
time.sleep(5)
aj3.back()
time.sleep(2)
